# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0002_auto_20160423_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionstatus',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
