# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0003_auto_20160424_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstatus',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
