# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0005_auto_20160424_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stud_diff',
            field=models.IntegerField(default=1),
        ),
    ]
