# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0006_question_stud_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
