# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0007_auto_20160430_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default='2016-09-01', null=True),
        ),
    ]
