# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0008_auto_20160430_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 21, 18, 18, 35, 79888, tzinfo=utc), null=True),
        ),
    ]
