# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0010_auto_20160430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 22, 20, 15, 6, 557486, tzinfo=utc), null=True),
        ),
    ]
