# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0013_auto_20160501_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 27, 16, 30, 54, 704066, tzinfo=utc), null=True),
        ),
    ]
