# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0015_auto_20160507_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 29, 21, 20, 15, 493138, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='questionstatus',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
