# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0016_auto_20160508_1506'),
        ('Problems', '0016_auto_20160508_1720'),
    ]

    operations = [
    ]
