# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='cur_poll',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='num_poll',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 1, 18, 37, 44, 679620, tzinfo=utc), null=True),
        ),
    ]
