# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0018_auto_20160511_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 1, 18, 47, 42, 779029, tzinfo=utc), null=True),
        ),
    ]
