# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0020_auto_20160511_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 1, 19, 57, 22, 988259, tzinfo=utc), null=True),
        ),
    ]
