# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0022_auto_20160511_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='can_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 3, 23, 27, 1, 787002, tzinfo=utc), null=True),
        ),
    ]
