# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0025_auto_20160514_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 4, 21, 32, 6, 850814, tzinfo=utc), null=True),
        ),
    ]
