# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0026_auto_20160514_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 12, 16, 54, 8, 42857, tzinfo=utc), null=True),
        ),
    ]
