# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0027_auto_20160522_1254'),
        ('Problems', '0029_auto_20160522_1310'),
    ]

    operations = [
    ]
