# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0030_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 12, 17, 40, 19, 257711, tzinfo=utc), null=True),
        ),
    ]
