# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0031_auto_20160522_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 20, 20, 4, 48, 902022, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
