# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0032_auto_20160522_1529'),
        ('Problems', '0032_auto_20160530_1604'),
    ]

    operations = [
    ]
