# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 21:34
from __future__ import unicode_literals

import Problems.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Problems', '0032_auto_20160530_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('doc_file', models.FileField(upload_to=Problems.models.content_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 22, 21, 34, 20, 465504, tzinfo=utc), null=True),
        ),
    ]
