# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0033_auto_20160601_1734'),
        ('Problems', '0033_merge'),
    ]

    operations = [
    ]
