# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0034_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 10, 18, 45, 16, 710610, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='doc_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='linkeddocument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.DocumentCategory'),
        ),
    ]
