# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0035_auto_20160619_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 10, 19, 21, 29, 857210, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='Problems.DocumentCategory'),
        ),
    ]
