# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 22:03
from __future__ import unicode_literals

import Problems.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0036_auto_20160619_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=Problems.models.get_localtime),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 26, 22, 3, 2, 299611, tzinfo=utc), null=True),
        ),
    ]
