# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0037_auto_20160705_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 26, 22, 11, 45, 344626, tzinfo=utc), null=True),
        ),
    ]
