# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0038_auto_20160705_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 27, 2, 32, 17, 108983, tzinfo=utc), null=True),
        ),
    ]
