# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0040_auto_20160706_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.Quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='out_of',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentquizresult',
            name='attempt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentquizresult',
            name='cur_quest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 13, 22, 59, 12, 185609, tzinfo=utc), null=True),
        ),
    ]
