# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0040_auto_20160708_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvote',
            name='question',
        ),
        migrations.AddField(
            model_name='studentvote',
            name='cur_poll',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 29, 23, 16, 12, 102408, tzinfo=utc), null=True),
        ),
    ]
