# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0041_auto_20160706_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markedquestion',
            options={'ordering': ['quiz', 'category']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 19, 25, 50, 937190, tzinfo=utc), null=True),
        ),
    ]
