# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0043_auto_20160707_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 21, 29, 57, 885485, tzinfo=utc), null=True),
        ),
    ]
