# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 00:25
from __future__ import unicode_literals

import Problems.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0044_auto_20160707_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedquestion',
            name='num_vars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 15, 0, 25, 14, 820530, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='category',
            field=models.IntegerField(default=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='choices',
            field=models.TextField(null=True, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='problem_str',
            field=models.TextField(verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=Problems.models.Quiz, to='Problems.Quiz'),
        ),
    ]
