# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0045_auto_20160707_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 16, 19, 33, 9, 547798, tzinfo=utc), null=True),
        ),
    ]
