# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0046_auto_20160708_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 8, 17, 22, 18, 80853, tzinfo=utc), null=True),
        ),
    ]
