# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0049_auto_20160711_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedquestion',
            name='functions',
            field=models.TextField(default=b'{}', verbose_name=b'Functions'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 18, 23, 2, 45, 113572, tzinfo=utc), null=True),
        ),
    ]
