# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0050_auto_20160711_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 2, 8, 31, 60263, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='functions',
            field=models.TextField(default='{}', verbose_name='Functions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires on'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='live',
            field=models.DateTimeField(verbose_name='Live on'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='out_of',
            field=models.IntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tries',
            field=models.IntegerField(default=0, verbose_name='Tries'),
        ),
        migrations.AlterField(
            model_name='studentquizresult',
            name='result',
            field=models.TextField(default='{}'),
        ),
    ]
