# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0051_auto_20160711_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 22, 33, 28, 603076, tzinfo=utc), null=True),
        ),
    ]
