# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0052_auto_20160712_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentquizresult',
            options={'verbose_name': 'Quiz Result'},
        ),
        migrations.AddField(
            model_name='markedquestion',
            name='mc_choices',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='markedquestion',
            name='q_type',
            field=models.CharField(choices=[('D', 'Direct Entry'), ('MC', 'Multiple Choice'), ('TF', 'True/False')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 2, 25, 12, 548528, tzinfo=utc), null=True),
        ),
    ]
