# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0054_auto_20160714_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 2, 42, 43, 95027, tzinfo=utc), null=True),
        ),
    ]
