# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0055_auto_20160714_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 3, 37, 6, 336250, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='functions',
            field=models.TextField(default='{}', verbose_name='Functions'),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='mc_choices',
            field=models.TextField(default='[]', null=True, verbose_name='Multiple Choice'),
        ),
    ]
