# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0057_auto_20160714_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 3, 39, 32, 920902, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='markedquestion',
            name='mc_choices',
            field=models.TextField(blank=True, default='[]', verbose_name='Multiple Choice'),
        ),
    ]
