# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0058_auto_20160714_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markedquestion',
            options={'ordering': ['quiz', 'category'], 'verbose_name': 'Marked Question'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 23, 15, 57, 408154, tzinfo=utc), null=True),
        ),
    ]
