# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0059_auto_20160715_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 22, 23, 16, 12, 672423, tzinfo=utc), null=True),
        ),
    ]
