# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0047_auto_20160718_1322'),
        ('Problems', '0060_auto_20160715_1916'),
    ]

    operations = [
    ]
