# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 20:11
from __future__ import unicode_literals

import Problems.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Problems', '0063_auto_20160725_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='/notes/', validators=[Problems.validators.FileValidator(content_types=('application/xml', 'image/jpeg', 'image/png'), max_size=512000)])),
                ('accepted', models.BooleanField(default=False)),
                ('exemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problems.ExemptionType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_studentdocument_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 13, 20, 11, 57, 492779, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='doc_file',
            field=models.FileField(upload_to='/notes/', validators=[Problems.validators.FileValidator(content_types=('application/xml', 'image/jpeg', 'image/png'), max_size=512000)]),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_linkeddocument_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
