# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 20:44
from __future__ import unicode_literals

import Problems.models
import Problems.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0064_auto_20160806_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 13, 20, 44, 30, 109659, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='doc_file',
            field=models.FileField(upload_to=Problems.models.directory_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png'), max_size=512000)]),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_file',
            field=models.FileField(upload_to=Problems.models.directory_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png'), max_size=512000)]),
        ),
    ]
