# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0065_auto_20160806_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 13, 21, 33, 40, 686575, tzinfo=utc), null=True),
        ),
    ]
