# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0068_auto_20160806_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 13, 22, 6, 15, 941821, tzinfo=utc), null=True),
        ),
    ]
