# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0072_auto_20160819_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='typo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
