# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 18:31
from __future__ import unicode_literals

import Problems.models
import Problems.validators
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Problems', '0073_typo_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='exemptiontype',
            name='out_of',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/tholden/djangotest/course_website/notes'), upload_to=Problems.models.note_name_setter, validators=[Problems.validators.FileValidator(content_types=(b'application/pdf', b'image/jpeg', b'image/png'), max_size=512000)]),
        ),
        migrations.AlterField(
            model_name='typo',
            name='document',
            field=models.CharField(choices=[(b'Mat134', b'Mat 134'), (b'Mat237', b'Mat 237')], max_length=100),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problems.ExemptionType'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
