# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0074_auto_20160824_1431'),
        ('Problems', '0074_studentinfo'),
    ]

    operations = [
    ]
