# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 17:06
from __future__ import unicode_literals

import Problems.models
import Problems.validators
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0075_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['user__username', 'category']},
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tholden/djangotest/course_website/notes'), upload_to=Problems.models.note_name_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png'), max_size=512000)]),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typo',
            name='document',
            field=models.CharField(choices=[('Mat137', 'Mat 137'), ('Mat134', 'Mat 134')], max_length=100),
        ),
    ]
