# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Problems', '0076_auto_20160907_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_enrol', models.IntegerField()),
                ('cur_enrol', models.IntegerField()),
                ('add_info', models.TextField(blank=True, null=True)),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['user', 'student_number', 'lecture', 'tutorial']},
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='tutorial_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.Tutorial'),
        ),
    ]
