# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 18:05
from __future__ import unicode_literals

from django.db import migrations

def link_students_tutorials(apps, schema_editor):
    Info = apps.get_model('Problems', 'StudentInfo')
    Tuts = apps.get_model('Problems', 'Tutorial')

    for info in Info.objects.all():
        try:
            tut = Tuts.objects.get(name=info.tutorial)
            info.tutorial_link = tut
            info.save()
        except:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0077_auto_20161211_1257'),
    ]

    operations = [
        migrations.RunPython(link_students_tutorials)
    ]
