# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0078_transfer_tutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['user', 'student_number', 'lecture', 'tutorial_link']},
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='tutorial',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='tutorial_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Problems.Tutorial'),
        ),
    ]
