# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0079_auto_20161211_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['user', 'student_number', 'lecture', 'tutorial']},
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='tutorial_link',
            new_name='tutorial',
        ),
    ]
