# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 23:02
from __future__ import unicode_literals

import Problems.models
import Problems.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0080_auto_20161211_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tholden/django/course_website/notes'), upload_to=Problems.models.note_name_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png'), max_size=1024000)]),
        ),
        migrations.AlterField(
            model_name='typo',
            name='document',
            field=models.CharField(choices=[('Mat134', 'Mat 134'), ('Mat237', 'Mat 237')], max_length=100),
        ),
    ]
