# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:20
from __future__ import unicode_literals

import Problems.models
import Problems.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0082_auto_20170410_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvbackup',
            name='doc_file',
            field=models.FileField(upload_to=Problems.models.directory_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png', 'text/plain'))]),
        ),
        migrations.AlterField(
            model_name='linkeddocument',
            name='doc_file',
            field=models.FileField(upload_to=Problems.models.directory_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png', 'text/plain'))]),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/note'), upload_to=Problems.models.note_name_setter, validators=[Problems.validators.FileValidator(content_types=('application/pdf', 'image/jpeg', 'image/png'), max_size=1024000)]),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
