# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0083_auto_20170412_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddocument',
            name='live_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
