# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0084_linkeddocument_live_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
