# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Thursday'), ('THU', 'Frday'), ('SAT', 'Saturday')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeblock', models.CharField(max_length=4)),
                ('dow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathhelproom.DayOfWeek')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_timeslots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('interval', models.IntegerField(default=30)),
                ('max_per_slot', models.IntegerField(default=3)),
                ('open_start', models.DateTimeField()),
                ('open_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('is_ta', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('num_blocks', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mhr_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeslots',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathhelproom.TimeTable'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='tod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tod_timeslots', to='mathhelproom.TimeOfDay'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dow', to='mathhelproom.TimeTable'),
        ),
    ]
