# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathhelproom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mhr_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
